# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GitHubUserPublicApiDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GitHubUserPublicApiDemo
	pod 'Alamofire'
	pod 'SDWebImage'

  target 'GitHubUserPublicApiDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GitHubUserPublicApiDemoUITests' do
    # Pods for testing
  end

end
